name: ex_audioplay
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  firebase_core: ^2.18.0  # Adiciona firebase_core para inicialização do Firebase
  cloud_firestore: 4.17.5  # Adiciona cloud_firestore para Firestore
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
